remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

permalink: pretty

github:
  is_project_page: false

title: GS Freshservice PoC 가이드
description: GS의 Freshservice 도입을 위한 PoC 가이드 및 자료
show_downloads: false
show_github_button: false

# 사이트 네비게이션 설정
navigation:
  - title: 홈
    url: /
  - title: 셀프 POC 가이드
    url: /self-service-poc/
  - title: PoC 전략
    url: /strategy/
  - title: ITSM 워크플로우
    url: /itsm-workflow/
  - title: 자산관리 워크플로우
    url: /asset-management/
  - title: 라이선스 권장사항
    url: /license-recommendations/
  - title: 프레젠테이션
    url: /presentation/
